// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/account.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package fr.antinote.antinote_app.protos;

@kotlin.jvm.JvmName("-initializeaccountRegistry")
public inline fun accountRegistry(block: fr.antinote.antinote_app.protos.AccountRegistryKt.Dsl.() -> kotlin.Unit): fr.antinote.antinote_app.protos.Account.AccountRegistry =
  fr.antinote.antinote_app.protos.AccountRegistryKt.Dsl._create(fr.antinote.antinote_app.protos.Account.AccountRegistry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `antinote_app.AccountRegistry`
 */
public object AccountRegistryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: fr.antinote.antinote_app.protos.Account.AccountRegistry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: fr.antinote.antinote_app.protos.Account.AccountRegistry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): fr.antinote.antinote_app.protos.Account.AccountRegistry = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AccountsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     */
     public val accounts: com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.accountsList
      )
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     * @param value The accounts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAccounts")
    public fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.add(value: fr.antinote.antinote_app.protos.Account.AntinoteAccount) {
      _builder.addAccounts(value)
    }
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     * @param value The accounts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.plusAssign(value: fr.antinote.antinote_app.protos.Account.AntinoteAccount) {
      add(value)
    }
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     * @param values The accounts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAccounts")
    public fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.addAll(values: kotlin.collections.Iterable<fr.antinote.antinote_app.protos.Account.AntinoteAccount>) {
      _builder.addAllAccounts(values)
    }
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     * @param values The accounts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAccounts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.plusAssign(values: kotlin.collections.Iterable<fr.antinote.antinote_app.protos.Account.AntinoteAccount>) {
      addAll(values)
    }
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     * @param index The index to set the value at.
     * @param value The accounts to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAccounts")
    public operator fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.set(index: kotlin.Int, value: fr.antinote.antinote_app.protos.Account.AntinoteAccount) {
      _builder.setAccounts(index, value)
    }
    /**
     * `repeated .antinote_app.AntinoteAccount accounts = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAccounts")
    public fun com.google.protobuf.kotlin.DslList<fr.antinote.antinote_app.protos.Account.AntinoteAccount, AccountsProxy>.clear() {
      _builder.clearAccounts()
    }

    /**
     * `optional string default_account_id = 2;`
     */
    public var defaultAccountId: kotlin.String
      @kotlin.jvm.JvmName("getDefaultAccountId")
        get() = _builder.defaultAccountId
      @kotlin.jvm.JvmName("setDefaultAccountId")
        set(value) {
        _builder.defaultAccountId = value
      }
    /**
     * `optional string default_account_id = 2;`
     */
    public fun clearDefaultAccountId() {
      _builder.clearDefaultAccountId()
    }
    /**
     * `optional string default_account_id = 2;`
     * @return Whether the defaultAccountId field is set.
     */
    public fun hasDefaultAccountId(): kotlin.Boolean {
      return _builder.hasDefaultAccountId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun fr.antinote.antinote_app.protos.Account.AccountRegistry.copy(block: `fr.antinote.antinote_app.protos`.AccountRegistryKt.Dsl.() -> kotlin.Unit): fr.antinote.antinote_app.protos.Account.AccountRegistry =
  `fr.antinote.antinote_app.protos`.AccountRegistryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

