// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/account.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package fr.antinote.antinote_app.protos;

@kotlin.jvm.JvmName("-initializeantinoteAccount")
public inline fun antinoteAccount(block: fr.antinote.antinote_app.protos.AntinoteAccountKt.Dsl.() -> kotlin.Unit): fr.antinote.antinote_app.protos.Account.AntinoteAccount =
  fr.antinote.antinote_app.protos.AntinoteAccountKt.Dsl._create(fr.antinote.antinote_app.protos.Account.AntinoteAccount.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `antinote_app.AntinoteAccount`
 */
public object AntinoteAccountKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): fr.antinote.antinote_app.protos.Account.AntinoteAccount = _builder.build()

    /**
     * ```
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * ```
     *
     * `string uid = 1;`
     */
    public var uid: kotlin.String
      @kotlin.jvm.JvmName("getUid")
        get() = _builder.uid
      @kotlin.jvm.JvmName("setUid")
        set(value) {
        _builder.uid = value
      }
    /**
     * ```
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * ```
     *
     * `string uid = 1;`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * ```
     * The full name of the account holder.
     * ```
     *
     * `string name = 2;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * The full name of the account holder.
     * ```
     *
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * The username of the account.
     * ```
     *
     * `string username = 3;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * ```
     * The username of the account.
     * ```
     *
     * `string username = 3;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * ```
     * The name of the establishment for the account.
     * ```
     *
     * `string establishment_name = 4;`
     */
    public var establishmentName: kotlin.String
      @kotlin.jvm.JvmName("getEstablishmentName")
        get() = _builder.establishmentName
      @kotlin.jvm.JvmName("setEstablishmentName")
        set(value) {
        _builder.establishmentName = value
      }
    /**
     * ```
     * The name of the establishment for the account.
     * ```
     *
     * `string establishment_name = 4;`
     */
    public fun clearEstablishmentName() {
      _builder.clearEstablishmentName()
    }

    /**
     * ```
     * The base URL of the instance this points to.
     * ```
     *
     * `string base_url = 5;`
     */
    public var baseUrl: kotlin.String
      @kotlin.jvm.JvmName("getBaseUrl")
        get() = _builder.baseUrl
      @kotlin.jvm.JvmName("setBaseUrl")
        set(value) {
        _builder.baseUrl = value
      }
    /**
     * ```
     * The base URL of the instance this points to.
     * ```
     *
     * `string base_url = 5;`
     */
    public fun clearBaseUrl() {
      _builder.clearBaseUrl()
    }

    /**
     * ```
     * The display name of the workspace this account is linked to.
     * ```
     *
     * `string workspace_name = 6;`
     */
    public var workspaceName: kotlin.String
      @kotlin.jvm.JvmName("getWorkspaceName")
        get() = _builder.workspaceName
      @kotlin.jvm.JvmName("setWorkspaceName")
        set(value) {
        _builder.workspaceName = value
      }
    /**
     * ```
     * The display name of the workspace this account is linked to.
     * ```
     *
     * `string workspace_name = 6;`
     */
    public fun clearWorkspaceName() {
      _builder.clearWorkspaceName()
    }

    /**
     * ```
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * ```
     *
     * `.google.protobuf.Any token_credentials = 7;`
     */
    public var tokenCredentials: com.google.protobuf.Any
      @kotlin.jvm.JvmName("getTokenCredentials")
        get() = _builder.tokenCredentials
      @kotlin.jvm.JvmName("setTokenCredentials")
        set(value) {
        _builder.tokenCredentials = value
      }
    /**
     * ```
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * ```
     *
     * `.google.protobuf.Any token_credentials = 7;`
     */
    public fun clearTokenCredentials() {
      _builder.clearTokenCredentials()
    }
    /**
     * ```
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * ```
     *
     * `.google.protobuf.Any token_credentials = 7;`
     * @return Whether the tokenCredentials field is set.
     */
    public fun hasTokenCredentials(): kotlin.Boolean {
      return _builder.hasTokenCredentials()
    }

    public val AntinoteAccountKt.Dsl.tokenCredentialsOrNull: com.google.protobuf.Any?
      get() = _builder.tokenCredentialsOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun fr.antinote.antinote_app.protos.Account.AntinoteAccount.copy(block: `fr.antinote.antinote_app.protos`.AntinoteAccountKt.Dsl.() -> kotlin.Unit): fr.antinote.antinote_app.protos.Account.AntinoteAccount =
  `fr.antinote.antinote_app.protos`.AntinoteAccountKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder.tokenCredentialsOrNull: com.google.protobuf.Any?
  get() = if (hasTokenCredentials()) getTokenCredentials() else null

