// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package fr.antinote.studies_management.antinote_app.pigeon_posts

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object NativeSyncPigeonUtils {

  fun createConnectionError(channelName: String): SyncManagerError {
    return SyncManagerError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is SyncManagerError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class SyncManagerError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class SyncResultType(val raw: Int) {
  /** When the sync completes successfully. */
  SUCCESS(0),
  /** When we can't access the remote or have temporary issues. */
  RETRY(1),
  /** When the credentials are invalid or the feature is unavailable. */
  FAILURE(2);

  companion object {
    fun ofRaw(raw: Int): SyncResultType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SyncMessageType(val raw: Int) {
  MISSING_CALENDAR_PERMISSION(0),
  MISSING_NOTIFICATION_PERMISSION(1);

  companion object {
    fun ofRaw(raw: Int): SyncMessageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncRequest (
  /** The account protobuf (without credentials) to perform the task. */
  val account: ByteArray,
  /**
   * The ID of the sync request type that may be forced (although it is may be
   * disabled).
   */
  val forcedScope: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncRequest {
      val account = pigeonVar_list[0] as ByteArray
      val forcedScope = pigeonVar_list[1] as List<Long>?
      return SyncRequest(account, forcedScope)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      account,
      forcedScope,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SyncRequest
    return NativeSyncPigeonUtils.deepEquals(this.account, other.account) && NativeSyncPigeonUtils.deepEquals(this.forcedScope, other.forcedScope)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.account)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.forcedScope)
    return result
  }
  override fun toString(): String {
    return "SyncRequest(account=${account.contentToString()}, forcedScope=$forcedScope)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncResponse (
  /** The result for the sync task. */
  val result: SyncResultType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncResponse {
      val result = pigeonVar_list[0] as SyncResultType
      return SyncResponse(result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      result,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SyncResponse
    return NativeSyncPigeonUtils.deepEquals(this.result, other.result)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.result)
    return result
  }
  override fun toString(): String {
    return "SyncResponse(result=$result)"
  }
}
private open class NativeSyncPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SyncResultType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SyncMessageType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SyncResultType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SyncMessageType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SyncRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SyncResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SyncManager(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SyncManager. */
    val codec: MessageCodec<Any?> by lazy {
      NativeSyncPigeonCodec()
    }
  }
  suspend fun syncAccount(requestArg: SyncRequest): SyncResponse
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.antinote_app.SyncManager.syncAccount$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(requestArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(SyncManagerError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(SyncManagerError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as SyncResponse
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(NativeSyncPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeSyncManager {
  /**
   * We use this as we can't easily know the locale in a non-Flutter
   * environment.
   */
  fun displayMessage(messageType: SyncMessageType)

  companion object {
    /** The codec used by NativeSyncManager. */
    val codec: MessageCodec<Any?> by lazy {
      NativeSyncPigeonCodec()
    }
    /** Sets up an instance of `NativeSyncManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeSyncManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeSyncManager.displayMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageTypeArg = args[0] as SyncMessageType
            val wrapped: List<Any?> = try {
              api.displayMessage(messageTypeArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeSyncPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
