// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package fr.antinote.studies_management.antinote_app.pigeon_posts

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeSyncPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is SyncManagerError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class SyncManagerError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class SyncResultType(val raw: Int) {
  /** When the sync completes successfully. */
  SUCCESS(0),
  /** When we get an invalid login exception. */
  AUTH(1),
  /** When we lose or never get to contact the PRONOTE instance. */
  AVAILABILITY(2),
  /**
   * When we have trouble actually parsing the different elements or writing
   * them to system.
   */
  PARSING(3);

  companion object {
    fun ofRaw(raw: Int): SyncResultType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncResult (
  val result: SyncResultType,
  val totalEntries: Long,
  val addedEntries: Long,
  val removedEntries: Long,
  val updatedEntries: Long,
  val dbIssue: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncResult {
      val result = pigeonVar_list[0] as SyncResultType
      val totalEntries = pigeonVar_list[1] as Long
      val addedEntries = pigeonVar_list[2] as Long
      val removedEntries = pigeonVar_list[3] as Long
      val updatedEntries = pigeonVar_list[4] as Long
      val dbIssue = pigeonVar_list[5] as Boolean
      return SyncResult(result, totalEntries, addedEntries, removedEntries, updatedEntries, dbIssue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      result,
      totalEntries,
      addedEntries,
      removedEntries,
      updatedEntries,
      dbIssue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SyncResult
    return NativeSyncPigeonUtils.deepEquals(this.result, other.result) && NativeSyncPigeonUtils.deepEquals(this.totalEntries, other.totalEntries) && NativeSyncPigeonUtils.deepEquals(this.addedEntries, other.addedEntries) && NativeSyncPigeonUtils.deepEquals(this.removedEntries, other.removedEntries) && NativeSyncPigeonUtils.deepEquals(this.updatedEntries, other.updatedEntries) && NativeSyncPigeonUtils.deepEquals(this.dbIssue, other.dbIssue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.result)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.totalEntries)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.addedEntries)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.removedEntries)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.updatedEntries)
    result = 31 * result + NativeSyncPigeonUtils.deepHash(this.dbIssue)
    return result
  }
}
private open class NativeSyncPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SyncResultType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SyncResultType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SyncResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeSyncManager {
  fun syncFinished(result: SyncResult)

  companion object {
    /** The codec used by NativeSyncManager. */
    val codec: MessageCodec<Any?> by lazy {
      NativeSyncPigeonCodec()
    }
    /** Sets up an instance of `NativeSyncManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeSyncManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeSyncManager.syncFinished$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val resultArg = args[0] as SyncResult
            val wrapped: List<Any?> = try {
              api.syncFinished(resultArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeSyncPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
