// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package fr.antinote.studies_management.antinote_app.pigeon_posts

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeCalendarPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is CalendarManagerError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class CalendarManagerError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class CalendarEventEntryType(val raw: Int) {
  CLAZZ(0);

  companion object {
    fun ofRaw(raw: Int): CalendarEventEntryType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AttendeeType(val raw: Int) {
  TEACHER(0),
  GROUP(1),
  CLASSROOM(2),
  HELPER(3);

  companion object {
    fun ofRaw(raw: Int): AttendeeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttendeeEntry (
  val name: String,
  val instanceDomain: String,
  val visualId: String,
  val type: AttendeeType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttendeeEntry {
      val name = pigeonVar_list[0] as String
      val instanceDomain = pigeonVar_list[1] as String
      val visualId = pigeonVar_list[2] as String
      val type = pigeonVar_list[3] as AttendeeType
      return AttendeeEntry(name, instanceDomain, visualId, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      instanceDomain,
      visualId,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttendeeEntry
    return NativeCalendarPigeonUtils.deepEquals(this.name, other.name) && NativeCalendarPigeonUtils.deepEquals(this.instanceDomain, other.instanceDomain) && NativeCalendarPigeonUtils.deepEquals(this.visualId, other.visualId) && NativeCalendarPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.name)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.instanceDomain)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.visualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.type)
    return result
  }
  override fun toString(): String {
    return "AttendeeEntry(name=$name, instanceDomain=$instanceDomain, visualId=$visualId, type=$type)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExistingCalendarEventEntry (
  val accountUid: String,
  val calendarId: Long,
  val id: Long,
  val originalVisualId: String? = null,
  val visualId: String,
  val rrule: String,
  val startTime: Long,
  val exceptions: List<Long>,
  val entryType: CalendarEventEntryType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExistingCalendarEventEntry {
      val accountUid = pigeonVar_list[0] as String
      val calendarId = pigeonVar_list[1] as Long
      val id = pigeonVar_list[2] as Long
      val originalVisualId = pigeonVar_list[3] as String?
      val visualId = pigeonVar_list[4] as String
      val rrule = pigeonVar_list[5] as String
      val startTime = pigeonVar_list[6] as Long
      val exceptions = pigeonVar_list[7] as List<Long>
      val entryType = pigeonVar_list[8] as CalendarEventEntryType
      return ExistingCalendarEventEntry(accountUid, calendarId, id, originalVisualId, visualId, rrule, startTime, exceptions, entryType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accountUid,
      calendarId,
      id,
      originalVisualId,
      visualId,
      rrule,
      startTime,
      exceptions,
      entryType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExistingCalendarEventEntry
    return NativeCalendarPigeonUtils.deepEquals(this.accountUid, other.accountUid) && NativeCalendarPigeonUtils.deepEquals(this.calendarId, other.calendarId) && NativeCalendarPigeonUtils.deepEquals(this.id, other.id) && NativeCalendarPigeonUtils.deepEquals(this.originalVisualId, other.originalVisualId) && NativeCalendarPigeonUtils.deepEquals(this.visualId, other.visualId) && NativeCalendarPigeonUtils.deepEquals(this.rrule, other.rrule) && NativeCalendarPigeonUtils.deepEquals(this.startTime, other.startTime) && NativeCalendarPigeonUtils.deepEquals(this.exceptions, other.exceptions) && NativeCalendarPigeonUtils.deepEquals(this.entryType, other.entryType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.accountUid)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.calendarId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.id)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.originalVisualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.visualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.rrule)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.startTime)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.exceptions)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.entryType)
    return result
  }
  override fun toString(): String {
    return "ExistingCalendarEventEntry(accountUid=$accountUid, calendarId=$calendarId, id=$id, originalVisualId=$originalVisualId, visualId=$visualId, rrule=$rrule, startTime=$startTime, exceptions=$exceptions, entryType=$entryType)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NewExceptionCalendarEventEntry (
  val start: Long,
  val end: Long,
  val title: String,
  val descriptions: String,
  val location: String? = null,
  val color: Long,
  val visualId: String,
  val canceled: Boolean,
  val attendees: List<AttendeeEntry>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NewExceptionCalendarEventEntry {
      val start = pigeonVar_list[0] as Long
      val end = pigeonVar_list[1] as Long
      val title = pigeonVar_list[2] as String
      val descriptions = pigeonVar_list[3] as String
      val location = pigeonVar_list[4] as String?
      val color = pigeonVar_list[5] as Long
      val visualId = pigeonVar_list[6] as String
      val canceled = pigeonVar_list[7] as Boolean
      val attendees = pigeonVar_list[8] as List<AttendeeEntry>
      return NewExceptionCalendarEventEntry(start, end, title, descriptions, location, color, visualId, canceled, attendees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      start,
      end,
      title,
      descriptions,
      location,
      color,
      visualId,
      canceled,
      attendees,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NewExceptionCalendarEventEntry
    return NativeCalendarPigeonUtils.deepEquals(this.start, other.start) && NativeCalendarPigeonUtils.deepEquals(this.end, other.end) && NativeCalendarPigeonUtils.deepEquals(this.title, other.title) && NativeCalendarPigeonUtils.deepEquals(this.descriptions, other.descriptions) && NativeCalendarPigeonUtils.deepEquals(this.location, other.location) && NativeCalendarPigeonUtils.deepEquals(this.color, other.color) && NativeCalendarPigeonUtils.deepEquals(this.visualId, other.visualId) && NativeCalendarPigeonUtils.deepEquals(this.canceled, other.canceled) && NativeCalendarPigeonUtils.deepEquals(this.attendees, other.attendees)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.start)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.end)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.title)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.descriptions)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.location)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.color)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.visualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.canceled)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.attendees)
    return result
  }
  override fun toString(): String {
    return "NewExceptionCalendarEventEntry(start=$start, end=$end, title=$title, descriptions=$descriptions, location=$location, color=$color, visualId=$visualId, canceled=$canceled, attendees=$attendees)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NewRecurringCalendarEventEntry (
  val accountUid: String,
  val mockStart: Long,
  val duration: String,
  val rrule: String? = null,
  val rdate: String? = null,
  val exdate: String,
  val calendarId: Long,
  val title: String,
  val descriptions: String,
  val location: String? = null,
  val color: Long,
  val allDay: Boolean,
  val visualId: String,
  val entryType: CalendarEventEntryType,
  val canceled: Boolean,
  val exceptions: List<NewExceptionCalendarEventEntry>,
  val attendees: List<AttendeeEntry>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NewRecurringCalendarEventEntry {
      val accountUid = pigeonVar_list[0] as String
      val mockStart = pigeonVar_list[1] as Long
      val duration = pigeonVar_list[2] as String
      val rrule = pigeonVar_list[3] as String?
      val rdate = pigeonVar_list[4] as String?
      val exdate = pigeonVar_list[5] as String
      val calendarId = pigeonVar_list[6] as Long
      val title = pigeonVar_list[7] as String
      val descriptions = pigeonVar_list[8] as String
      val location = pigeonVar_list[9] as String?
      val color = pigeonVar_list[10] as Long
      val allDay = pigeonVar_list[11] as Boolean
      val visualId = pigeonVar_list[12] as String
      val entryType = pigeonVar_list[13] as CalendarEventEntryType
      val canceled = pigeonVar_list[14] as Boolean
      val exceptions = pigeonVar_list[15] as List<NewExceptionCalendarEventEntry>
      val attendees = pigeonVar_list[16] as List<AttendeeEntry>
      return NewRecurringCalendarEventEntry(accountUid, mockStart, duration, rrule, rdate, exdate, calendarId, title, descriptions, location, color, allDay, visualId, entryType, canceled, exceptions, attendees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accountUid,
      mockStart,
      duration,
      rrule,
      rdate,
      exdate,
      calendarId,
      title,
      descriptions,
      location,
      color,
      allDay,
      visualId,
      entryType,
      canceled,
      exceptions,
      attendees,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NewRecurringCalendarEventEntry
    return NativeCalendarPigeonUtils.deepEquals(this.accountUid, other.accountUid) && NativeCalendarPigeonUtils.deepEquals(this.mockStart, other.mockStart) && NativeCalendarPigeonUtils.deepEquals(this.duration, other.duration) && NativeCalendarPigeonUtils.deepEquals(this.rrule, other.rrule) && NativeCalendarPigeonUtils.deepEquals(this.rdate, other.rdate) && NativeCalendarPigeonUtils.deepEquals(this.exdate, other.exdate) && NativeCalendarPigeonUtils.deepEquals(this.calendarId, other.calendarId) && NativeCalendarPigeonUtils.deepEquals(this.title, other.title) && NativeCalendarPigeonUtils.deepEquals(this.descriptions, other.descriptions) && NativeCalendarPigeonUtils.deepEquals(this.location, other.location) && NativeCalendarPigeonUtils.deepEquals(this.color, other.color) && NativeCalendarPigeonUtils.deepEquals(this.allDay, other.allDay) && NativeCalendarPigeonUtils.deepEquals(this.visualId, other.visualId) && NativeCalendarPigeonUtils.deepEquals(this.entryType, other.entryType) && NativeCalendarPigeonUtils.deepEquals(this.canceled, other.canceled) && NativeCalendarPigeonUtils.deepEquals(this.exceptions, other.exceptions) && NativeCalendarPigeonUtils.deepEquals(this.attendees, other.attendees)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.accountUid)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.mockStart)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.duration)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.rrule)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.rdate)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.exdate)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.calendarId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.title)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.descriptions)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.location)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.color)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.allDay)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.visualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.entryType)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.canceled)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.exceptions)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.attendees)
    return result
  }
  override fun toString(): String {
    return "NewRecurringCalendarEventEntry(accountUid=$accountUid, mockStart=$mockStart, duration=$duration, rrule=$rrule, rdate=$rdate, exdate=$exdate, calendarId=$calendarId, title=$title, descriptions=$descriptions, location=$location, color=$color, allDay=$allDay, visualId=$visualId, entryType=$entryType, canceled=$canceled, exceptions=$exceptions, attendees=$attendees)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExistingCalendarEntry (
  val accountUid: String,
  val resourceVisualId: String,
  val id: Long,
  val displayName: String,
  val color: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExistingCalendarEntry {
      val accountUid = pigeonVar_list[0] as String
      val resourceVisualId = pigeonVar_list[1] as String
      val id = pigeonVar_list[2] as Long
      val displayName = pigeonVar_list[3] as String
      val color = pigeonVar_list[4] as Long
      return ExistingCalendarEntry(accountUid, resourceVisualId, id, displayName, color)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accountUid,
      resourceVisualId,
      id,
      displayName,
      color,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExistingCalendarEntry
    return NativeCalendarPigeonUtils.deepEquals(this.accountUid, other.accountUid) && NativeCalendarPigeonUtils.deepEquals(this.resourceVisualId, other.resourceVisualId) && NativeCalendarPigeonUtils.deepEquals(this.id, other.id) && NativeCalendarPigeonUtils.deepEquals(this.displayName, other.displayName) && NativeCalendarPigeonUtils.deepEquals(this.color, other.color)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.accountUid)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.resourceVisualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.id)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.displayName)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.color)
    return result
  }
  override fun toString(): String {
    return "ExistingCalendarEntry(accountUid=$accountUid, resourceVisualId=$resourceVisualId, id=$id, displayName=$displayName, color=$color)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NewCalendarEntry (
  val displayName: String,
  val accountUid: String,
  val resourceVisualId: String,
  val color: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NewCalendarEntry {
      val displayName = pigeonVar_list[0] as String
      val accountUid = pigeonVar_list[1] as String
      val resourceVisualId = pigeonVar_list[2] as String
      val color = pigeonVar_list[3] as Long
      return NewCalendarEntry(displayName, accountUid, resourceVisualId, color)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      displayName,
      accountUid,
      resourceVisualId,
      color,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NewCalendarEntry
    return NativeCalendarPigeonUtils.deepEquals(this.displayName, other.displayName) && NativeCalendarPigeonUtils.deepEquals(this.accountUid, other.accountUid) && NativeCalendarPigeonUtils.deepEquals(this.resourceVisualId, other.resourceVisualId) && NativeCalendarPigeonUtils.deepEquals(this.color, other.color)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.displayName)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.accountUid)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.resourceVisualId)
    result = 31 * result + NativeCalendarPigeonUtils.deepHash(this.color)
    return result
  }
  override fun toString(): String {
    return "NewCalendarEntry(displayName=$displayName, accountUid=$accountUid, resourceVisualId=$resourceVisualId, color=$color)"
  }
}
private open class NativeCalendarPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CalendarEventEntryType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AttendeeType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttendeeEntry.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExistingCalendarEventEntry.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NewExceptionCalendarEventEntry.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NewRecurringCalendarEventEntry.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExistingCalendarEntry.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NewCalendarEntry.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CalendarEventEntryType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AttendeeType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AttendeeEntry -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ExistingCalendarEventEntry -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NewExceptionCalendarEventEntry -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NewRecurringCalendarEventEntry -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ExistingCalendarEntry -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NewCalendarEntry -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeCalendarManager {
  fun listExisting(accountUid: String, calendarId: Long): List<ExistingCalendarEventEntry>
  fun listCalendars(accountUid: String): List<ExistingCalendarEntry>
  fun deleteCalendar(accountUid: String, calendarId: Long)
  fun insertNew(entries: List<NewRecurringCalendarEventEntry>)
  fun deleteExisting(entries: List<ExistingCalendarEventEntry>)
  fun insertNewCalendar(calendar: NewCalendarEntry): ExistingCalendarEntry

  companion object {
    /** The codec used by NativeCalendarManager. */
    val codec: MessageCodec<Any?> by lazy {
      NativeCalendarPigeonCodec()
    }
    /** Sets up an instance of `NativeCalendarManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeCalendarManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.listExisting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountUidArg = args[0] as String
            val calendarIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.listExisting(accountUidArg, calendarIdArg))
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.listCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountUidArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.listCalendars(accountUidArg))
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.deleteCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountUidArg = args[0] as String
            val calendarIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.deleteCalendar(accountUidArg, calendarIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.insertNew$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entriesArg = args[0] as List<NewRecurringCalendarEventEntry>
            val wrapped: List<Any?> = try {
              api.insertNew(entriesArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.deleteExisting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entriesArg = args[0] as List<ExistingCalendarEventEntry>
            val wrapped: List<Any?> = try {
              api.deleteExisting(entriesArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.antinote_app.NativeCalendarManager.insertNewCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarArg = args[0] as NewCalendarEntry
            val wrapped: List<Any?> = try {
              listOf(api.insertNewCalendar(calendarArg))
            } catch (exception: Throwable) {
              NativeCalendarPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
