include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - augmentations
  exclude:
    - packages/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # We want to justify not using constant constructors (as those are faster)
    # rather than the inverse.
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true

    # This is to be consistent with the main package, which is older and
    # larger.
    prefer_single_quotes: true

    always_specify_types: false
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true

    avoid_empty_else: true
    avoid_relative_lib_imports: true

    use_key_in_widget_constructors: true
    prefer_final_fields: true

    implementation_imports: error

code-style:
  format: true

formatter:
  page_width: 80