name: antinote_app
description: "La solution !"
publish_to: "none"
version: 0.1.0+000100
repository: https://github.com/ANTINOTE-project/antinote_app

environment:
  sdk: ^3.13.0-234.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  antinote_api:
    git: https://github.com/ANTINOTE-project/antinote_api.git

  # Logging
  logging: ^1.3.0

  # Frontend - aesthetics
  hugeicons_pro: ^0.0.3
  skeletonizer: ^2.1.3
  dynamic_color: ^2.1.0
  intl: any

  # Frontend - useful
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  mobile_scanner: ^7.2.0
  flutter_widget_from_html_core: ^0.17.2

  # Backend
  html: ^0.15.6
  rrule: ^0.2.18
  protobuf: ^6.0.0
  shared_preferences: ^2.5.5
  uuid: ^4.5.3
  http: ^1.6.0
  collection: ^1.19.1
  image_picker: ^1.2.3
  # Disabled because it doesn't play nicely with R8
  #  cryptography_flutter_plus: ^3.0.2 # So that cryptography_plus in antinote is faster.

  material_ui: any

dependency_overrides:
  dynamic_color:
    git:
      url: "https://github.com/helomri/flutter-packages.git"
      path: "packages/dynamic_color"
      ref: feat/new-apis

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  pigeon: ^28.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SNPro
      fonts:
        - asset: assets/fonts/SNPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SNPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SNPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SNPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SNPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SNPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SNPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SNPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SNPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SNPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SNPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SNPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SNPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SNPro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SNPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SNPro-BlackItalic.ttf
          weight: 900
          style: italic