name: antinote_app
description: "La solution !"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.0-234.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  antinote:
    git: https://github.com/ANTINOTE-project/antinote.git

  # Logging
  logging: ^1.3.0
  talker: ^5.1.17 # TODO: remove this to only keep logging.

  # Frontend - aesthetics
  hugeicons_pro: ^0.0.3
  skeletonizer: ^2.1.3
  dynamic_color:
    path: ../material-flutter-packages/packages/dynamic_color
  intl: any

  # Frontend - useful
  go_router: ^17.2.3
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  mobile_scanner: ^7.2.0
  flutter_widget_from_html_core: ^0.17.2

  # Backend
  html: ^0.15.6
  rrule: ^0.2.18
  protobuf: ^6.0.0
  shared_preferences: ^2.5.5
  uuid: ^4.5.3
  http: ^1.6.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  pigeon: ^27.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SNPro
      fonts:
        - asset: assets/fonts/SNPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SNPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/SNPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SNPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SNPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SNPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SNPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SNPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SNPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SNPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SNPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SNPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SNPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SNPro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SNPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SNPro-BlackItalic.ttf
          weight: 900
          style: italic