// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum CalendarEventEntryType {
  clazz,
}

enum AttendeeType {
  teacher,
  group,
  classroom,
  helper,
}

class AttendeeEntry {
  AttendeeEntry({
    required this.name,
    required this.instanceDomain,
    required this.visualId,
    required this.type,
  });

  String name;

  String instanceDomain;

  String visualId;

  AttendeeType type;

  List<Object?> _toList() {
    return <Object?>[
      name,
      instanceDomain,
      visualId,
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttendeeEntry decode(Object result) {
    result as List<Object?>;
    return AttendeeEntry(
      name: result[0]! as String,
      instanceDomain: result[1]! as String,
      visualId: result[2]! as String,
      type: result[3]! as AttendeeType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttendeeEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(instanceDomain, other.instanceDomain) && _deepEquals(visualId, other.visualId) && _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ExistingCalendarEventEntry {
  ExistingCalendarEventEntry({
    required this.accountUid,
    required this.calendarId,
    required this.id,
    this.originalVisualId,
    required this.visualId,
    required this.rrule,
    required this.startTime,
    required this.exceptions,
    required this.entryType,
  });

  String accountUid;

  int calendarId;

  int id;

  String? originalVisualId;

  String visualId;

  String rrule;

  int startTime;

  List<int> exceptions;

  CalendarEventEntryType entryType;

  List<Object?> _toList() {
    return <Object?>[
      accountUid,
      calendarId,
      id,
      originalVisualId,
      visualId,
      rrule,
      startTime,
      exceptions,
      entryType,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExistingCalendarEventEntry decode(Object result) {
    result as List<Object?>;
    return ExistingCalendarEventEntry(
      accountUid: result[0]! as String,
      calendarId: result[1]! as int,
      id: result[2]! as int,
      originalVisualId: result[3] as String?,
      visualId: result[4]! as String,
      rrule: result[5]! as String,
      startTime: result[6]! as int,
      exceptions: (result[7]! as List<Object?>).cast<int>(),
      entryType: result[8]! as CalendarEventEntryType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExistingCalendarEventEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accountUid, other.accountUid) && _deepEquals(calendarId, other.calendarId) && _deepEquals(id, other.id) && _deepEquals(originalVisualId, other.originalVisualId) && _deepEquals(visualId, other.visualId) && _deepEquals(rrule, other.rrule) && _deepEquals(startTime, other.startTime) && _deepEquals(exceptions, other.exceptions) && _deepEquals(entryType, other.entryType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NewExceptionCalendarEventEntry {
  NewExceptionCalendarEventEntry({
    required this.start,
    required this.end,
    required this.title,
    required this.descriptions,
    this.location,
    required this.color,
    required this.visualId,
    required this.canceled,
    required this.attendees,
  });

  int start;

  int end;

  String title;

  String descriptions;

  String? location;

  int color;

  String visualId;

  bool canceled;

  List<AttendeeEntry> attendees;

  List<Object?> _toList() {
    return <Object?>[
      start,
      end,
      title,
      descriptions,
      location,
      color,
      visualId,
      canceled,
      attendees,
    ];
  }

  Object encode() {
    return _toList();  }

  static NewExceptionCalendarEventEntry decode(Object result) {
    result as List<Object?>;
    return NewExceptionCalendarEventEntry(
      start: result[0]! as int,
      end: result[1]! as int,
      title: result[2]! as String,
      descriptions: result[3]! as String,
      location: result[4] as String?,
      color: result[5]! as int,
      visualId: result[6]! as String,
      canceled: result[7]! as bool,
      attendees: (result[8]! as List<Object?>).cast<AttendeeEntry>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NewExceptionCalendarEventEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(start, other.start) && _deepEquals(end, other.end) && _deepEquals(title, other.title) && _deepEquals(descriptions, other.descriptions) && _deepEquals(location, other.location) && _deepEquals(color, other.color) && _deepEquals(visualId, other.visualId) && _deepEquals(canceled, other.canceled) && _deepEquals(attendees, other.attendees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NewRecurringCalendarEventEntry {
  NewRecurringCalendarEventEntry({
    required this.accountUid,
    required this.mockStart,
    required this.duration,
    this.rrule,
    this.rdate,
    required this.exdate,
    required this.calendarId,
    required this.title,
    required this.descriptions,
    this.location,
    required this.color,
    required this.allDay,
    required this.visualId,
    required this.entryType,
    required this.canceled,
    required this.exceptions,
    required this.attendees,
  });

  String accountUid;

  int mockStart;

  String duration;

  String? rrule;

  String? rdate;

  String exdate;

  int calendarId;

  String title;

  String descriptions;

  String? location;

  int color;

  bool allDay;

  String visualId;

  CalendarEventEntryType entryType;

  bool canceled;

  List<NewExceptionCalendarEventEntry> exceptions;

  List<AttendeeEntry> attendees;

  List<Object?> _toList() {
    return <Object?>[
      accountUid,
      mockStart,
      duration,
      rrule,
      rdate,
      exdate,
      calendarId,
      title,
      descriptions,
      location,
      color,
      allDay,
      visualId,
      entryType,
      canceled,
      exceptions,
      attendees,
    ];
  }

  Object encode() {
    return _toList();  }

  static NewRecurringCalendarEventEntry decode(Object result) {
    result as List<Object?>;
    return NewRecurringCalendarEventEntry(
      accountUid: result[0]! as String,
      mockStart: result[1]! as int,
      duration: result[2]! as String,
      rrule: result[3] as String?,
      rdate: result[4] as String?,
      exdate: result[5]! as String,
      calendarId: result[6]! as int,
      title: result[7]! as String,
      descriptions: result[8]! as String,
      location: result[9] as String?,
      color: result[10]! as int,
      allDay: result[11]! as bool,
      visualId: result[12]! as String,
      entryType: result[13]! as CalendarEventEntryType,
      canceled: result[14]! as bool,
      exceptions: (result[15]! as List<Object?>).cast<NewExceptionCalendarEventEntry>(),
      attendees: (result[16]! as List<Object?>).cast<AttendeeEntry>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NewRecurringCalendarEventEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accountUid, other.accountUid) && _deepEquals(mockStart, other.mockStart) && _deepEquals(duration, other.duration) && _deepEquals(rrule, other.rrule) && _deepEquals(rdate, other.rdate) && _deepEquals(exdate, other.exdate) && _deepEquals(calendarId, other.calendarId) && _deepEquals(title, other.title) && _deepEquals(descriptions, other.descriptions) && _deepEquals(location, other.location) && _deepEquals(color, other.color) && _deepEquals(allDay, other.allDay) && _deepEquals(visualId, other.visualId) && _deepEquals(entryType, other.entryType) && _deepEquals(canceled, other.canceled) && _deepEquals(exceptions, other.exceptions) && _deepEquals(attendees, other.attendees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ExistingCalendarEntry {
  ExistingCalendarEntry({
    required this.accountUid,
    required this.resourceVisualId,
    required this.id,
    required this.displayName,
    required this.color,
  });

  String accountUid;

  String resourceVisualId;

  int id;

  String displayName;

  int color;

  List<Object?> _toList() {
    return <Object?>[
      accountUid,
      resourceVisualId,
      id,
      displayName,
      color,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExistingCalendarEntry decode(Object result) {
    result as List<Object?>;
    return ExistingCalendarEntry(
      accountUid: result[0]! as String,
      resourceVisualId: result[1]! as String,
      id: result[2]! as int,
      displayName: result[3]! as String,
      color: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExistingCalendarEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accountUid, other.accountUid) && _deepEquals(resourceVisualId, other.resourceVisualId) && _deepEquals(id, other.id) && _deepEquals(displayName, other.displayName) && _deepEquals(color, other.color);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NewCalendarEntry {
  NewCalendarEntry({
    required this.displayName,
    required this.accountUid,
    required this.resourceVisualId,
    required this.color,
  });

  String displayName;

  String accountUid;

  String resourceVisualId;

  int color;

  List<Object?> _toList() {
    return <Object?>[
      displayName,
      accountUid,
      resourceVisualId,
      color,
    ];
  }

  Object encode() {
    return _toList();  }

  static NewCalendarEntry decode(Object result) {
    result as List<Object?>;
    return NewCalendarEntry(
      displayName: result[0]! as String,
      accountUid: result[1]! as String,
      resourceVisualId: result[2]! as String,
      color: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NewCalendarEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(displayName, other.displayName) && _deepEquals(accountUid, other.accountUid) && _deepEquals(resourceVisualId, other.resourceVisualId) && _deepEquals(color, other.color);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CalendarEventEntryType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AttendeeType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AttendeeEntry) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ExistingCalendarEventEntry) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NewExceptionCalendarEventEntry) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NewRecurringCalendarEventEntry) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ExistingCalendarEntry) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is NewCalendarEntry) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CalendarEventEntryType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AttendeeType.values[value];
      case 131:
        return AttendeeEntry.decode(readValue(buffer)!);
      case 132:
        return ExistingCalendarEventEntry.decode(readValue(buffer)!);
      case 133:
        return NewExceptionCalendarEventEntry.decode(readValue(buffer)!);
      case 134:
        return NewRecurringCalendarEventEntry.decode(readValue(buffer)!);
      case 135:
        return ExistingCalendarEntry.decode(readValue(buffer)!);
      case 136:
        return NewCalendarEntry.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeCalendarManager {
  /// Constructor for [NativeCalendarManager].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeCalendarManager({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<ExistingCalendarEventEntry>> listExisting(String accountUid, int calendarId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.listExisting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[accountUid, calendarId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ExistingCalendarEventEntry>();
  }

  Future<List<ExistingCalendarEntry>> listCalendars(String accountUid) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.listCalendars$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[accountUid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ExistingCalendarEntry>();
  }

  Future<void> deleteCalendar(String accountUid, int calendarId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.deleteCalendar$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[accountUid, calendarId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> insertNew(List<NewRecurringCalendarEventEntry> entries) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.insertNew$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entries]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> deleteExisting(List<ExistingCalendarEventEntry> entries) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.deleteExisting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entries]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ExistingCalendarEntry> insertNewCalendar(NewCalendarEntry calendar) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.antinote_app.NativeCalendarManager.insertNewCalendar$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[calendar]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ExistingCalendarEntry;
  }
}
