// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/account.proto
// Protobuf Java Version: 4.34.1

package fr.antinote.antinote_app.protos;

@com.google.protobuf.Generated
public final class Account extends com.google.protobuf.GeneratedFile {
  private Account() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Account");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AntinoteAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:antinote_app.AntinoteAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * The full name of the account holder.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * The full name of the account holder.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * The username of the account.
     * </pre>
     *
     * <code>string username = 3;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <pre>
     * The username of the account.
     * </pre>
     *
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     * The name of the establishment for the account.
     * </pre>
     *
     * <code>string establishment_name = 4;</code>
     * @return The establishmentName.
     */
    java.lang.String getEstablishmentName();
    /**
     * <pre>
     * The name of the establishment for the account.
     * </pre>
     *
     * <code>string establishment_name = 4;</code>
     * @return The bytes for establishmentName.
     */
    com.google.protobuf.ByteString
        getEstablishmentNameBytes();

    /**
     * <pre>
     * The base URL of the instance this points to.
     * </pre>
     *
     * <code>string base_url = 5;</code>
     * @return The baseUrl.
     */
    java.lang.String getBaseUrl();
    /**
     * <pre>
     * The base URL of the instance this points to.
     * </pre>
     *
     * <code>string base_url = 5;</code>
     * @return The bytes for baseUrl.
     */
    com.google.protobuf.ByteString
        getBaseUrlBytes();

    /**
     * <pre>
     * The display name of the workspace this account is linked to.
     * </pre>
     *
     * <code>string workspace_name = 6;</code>
     * @return The workspaceName.
     */
    java.lang.String getWorkspaceName();
    /**
     * <pre>
     * The display name of the workspace this account is linked to.
     * </pre>
     *
     * <code>string workspace_name = 6;</code>
     * @return The bytes for workspaceName.
     */
    com.google.protobuf.ByteString
        getWorkspaceNameBytes();

    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     * @return Whether the tokenCredentials field is set.
     */
    boolean hasTokenCredentials();
    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     * @return The tokenCredentials.
     */
    com.google.protobuf.Any getTokenCredentials();
    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     */
    com.google.protobuf.AnyOrBuilder getTokenCredentialsOrBuilder();
  }
  /**
   * Protobuf type {@code antinote_app.AntinoteAccount}
   */
  public static final class AntinoteAccount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:antinote_app.AntinoteAccount)
      AntinoteAccountOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "AntinoteAccount");
    }
    // Use AntinoteAccount.newBuilder() to construct.
    private AntinoteAccount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AntinoteAccount() {
      uid_ = "";
      name_ = "";
      username_ = "";
      establishmentName_ = "";
      baseUrl_ = "";
      workspaceName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.antinote.antinote_app.protos.Account.AntinoteAccount.class, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uid_ = "";
    /**
     * <pre>
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * An internal Unique IDentifier used as a primary key to reference accounts
     * throughout the app.
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * The full name of the account holder.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The full name of the account holder.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <pre>
     * The username of the account.
     * </pre>
     *
     * <code>string username = 3;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The username of the account.
     * </pre>
     *
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ESTABLISHMENT_NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object establishmentName_ = "";
    /**
     * <pre>
     * The name of the establishment for the account.
     * </pre>
     *
     * <code>string establishment_name = 4;</code>
     * @return The establishmentName.
     */
    @java.lang.Override
    public java.lang.String getEstablishmentName() {
      java.lang.Object ref = establishmentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        establishmentName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The name of the establishment for the account.
     * </pre>
     *
     * <code>string establishment_name = 4;</code>
     * @return The bytes for establishmentName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEstablishmentNameBytes() {
      java.lang.Object ref = establishmentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        establishmentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE_URL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object baseUrl_ = "";
    /**
     * <pre>
     * The base URL of the instance this points to.
     * </pre>
     *
     * <code>string base_url = 5;</code>
     * @return The baseUrl.
     */
    @java.lang.Override
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The base URL of the instance this points to.
     * </pre>
     *
     * <code>string base_url = 5;</code>
     * @return The bytes for baseUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKSPACE_NAME_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object workspaceName_ = "";
    /**
     * <pre>
     * The display name of the workspace this account is linked to.
     * </pre>
     *
     * <code>string workspace_name = 6;</code>
     * @return The workspaceName.
     */
    @java.lang.Override
    public java.lang.String getWorkspaceName() {
      java.lang.Object ref = workspaceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workspaceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The display name of the workspace this account is linked to.
     * </pre>
     *
     * <code>string workspace_name = 6;</code>
     * @return The bytes for workspaceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkspaceNameBytes() {
      java.lang.Object ref = workspaceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workspaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_CREDENTIALS_FIELD_NUMBER = 7;
    private com.google.protobuf.Any tokenCredentials_;
    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     * @return Whether the tokenCredentials field is set.
     */
    @java.lang.Override
    public boolean hasTokenCredentials() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     * @return The tokenCredentials.
     */
    @java.lang.Override
    public com.google.protobuf.Any getTokenCredentials() {
      return tokenCredentials_ == null ? com.google.protobuf.Any.getDefaultInstance() : tokenCredentials_;
    }
    /**
     * <pre>
     * The actual identifiers for the account. Some informations within it may be
     * duplicated.
     * </pre>
     *
     * <code>.google.protobuf.Any token_credentials = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getTokenCredentialsOrBuilder() {
      return tokenCredentials_ == null ? com.google.protobuf.Any.getDefaultInstance() : tokenCredentials_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(establishmentName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, establishmentName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(baseUrl_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, baseUrl_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, workspaceName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(7, getTokenCredentials());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(establishmentName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, establishmentName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(baseUrl_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, baseUrl_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, workspaceName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getTokenCredentials());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.antinote.antinote_app.protos.Account.AntinoteAccount)) {
        return super.equals(obj);
      }
      fr.antinote.antinote_app.protos.Account.AntinoteAccount other = (fr.antinote.antinote_app.protos.Account.AntinoteAccount) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getEstablishmentName()
          .equals(other.getEstablishmentName())) return false;
      if (!getBaseUrl()
          .equals(other.getBaseUrl())) return false;
      if (!getWorkspaceName()
          .equals(other.getWorkspaceName())) return false;
      if (hasTokenCredentials() != other.hasTokenCredentials()) return false;
      if (hasTokenCredentials()) {
        if (!getTokenCredentials()
            .equals(other.getTokenCredentials())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + ESTABLISHMENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEstablishmentName().hashCode();
      hash = (37 * hash) + BASE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getBaseUrl().hashCode();
      hash = (37 * hash) + WORKSPACE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getWorkspaceName().hashCode();
      if (hasTokenCredentials()) {
        hash = (37 * hash) + TOKEN_CREDENTIALS_FIELD_NUMBER;
        hash = (53 * hash) + getTokenCredentials().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.antinote.antinote_app.protos.Account.AntinoteAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code antinote_app.AntinoteAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:antinote_app.AntinoteAccount)
        fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.antinote.antinote_app.protos.Account.AntinoteAccount.class, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder.class);
      }

      // Construct using fr.antinote.antinote_app.protos.Account.AntinoteAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetTokenCredentialsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uid_ = "";
        name_ = "";
        username_ = "";
        establishmentName_ = "";
        baseUrl_ = "";
        workspaceName_ = "";
        tokenCredentials_ = null;
        if (tokenCredentialsBuilder_ != null) {
          tokenCredentialsBuilder_.dispose();
          tokenCredentialsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AntinoteAccount_descriptor;
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount getDefaultInstanceForType() {
        return fr.antinote.antinote_app.protos.Account.AntinoteAccount.getDefaultInstance();
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount build() {
        fr.antinote.antinote_app.protos.Account.AntinoteAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount buildPartial() {
        fr.antinote.antinote_app.protos.Account.AntinoteAccount result = new fr.antinote.antinote_app.protos.Account.AntinoteAccount(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fr.antinote.antinote_app.protos.Account.AntinoteAccount result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uid_ = uid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.establishmentName_ = establishmentName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.baseUrl_ = baseUrl_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.workspaceName_ = workspaceName_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.tokenCredentials_ = tokenCredentialsBuilder_ == null
              ? tokenCredentials_
              : tokenCredentialsBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.antinote.antinote_app.protos.Account.AntinoteAccount) {
          return mergeFrom((fr.antinote.antinote_app.protos.Account.AntinoteAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.antinote.antinote_app.protos.Account.AntinoteAccount other) {
        if (other == fr.antinote.antinote_app.protos.Account.AntinoteAccount.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEstablishmentName().isEmpty()) {
          establishmentName_ = other.establishmentName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getBaseUrl().isEmpty()) {
          baseUrl_ = other.baseUrl_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getWorkspaceName().isEmpty()) {
          workspaceName_ = other.workspaceName_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasTokenCredentials()) {
          mergeTokenCredentials(other.getTokenCredentials());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                establishmentName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                baseUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                workspaceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    internalGetTokenCredentialsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * An internal Unique IDentifier used as a primary key to reference accounts
       * throughout the app.
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An internal Unique IDentifier used as a primary key to reference accounts
       * throughout the app.
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An internal Unique IDentifier used as a primary key to reference accounts
       * throughout the app.
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An internal Unique IDentifier used as a primary key to reference accounts
       * throughout the app.
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        uid_ = getDefaultInstance().getUid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An internal Unique IDentifier used as a primary key to reference accounts
       * throughout the app.
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * The full name of the account holder.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The full name of the account holder.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The full name of the account holder.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The full name of the account holder.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The full name of the account holder.
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <pre>
       * The username of the account.
       * </pre>
       *
       * <code>string username = 3;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The username of the account.
       * </pre>
       *
       * <code>string username = 3;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The username of the account.
       * </pre>
       *
       * <code>string username = 3;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The username of the account.
       * </pre>
       *
       * <code>string username = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The username of the account.
       * </pre>
       *
       * <code>string username = 3;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object establishmentName_ = "";
      /**
       * <pre>
       * The name of the establishment for the account.
       * </pre>
       *
       * <code>string establishment_name = 4;</code>
       * @return The establishmentName.
       */
      public java.lang.String getEstablishmentName() {
        java.lang.Object ref = establishmentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          establishmentName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The name of the establishment for the account.
       * </pre>
       *
       * <code>string establishment_name = 4;</code>
       * @return The bytes for establishmentName.
       */
      public com.google.protobuf.ByteString
          getEstablishmentNameBytes() {
        java.lang.Object ref = establishmentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          establishmentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name of the establishment for the account.
       * </pre>
       *
       * <code>string establishment_name = 4;</code>
       * @param value The establishmentName to set.
       * @return This builder for chaining.
       */
      public Builder setEstablishmentName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        establishmentName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the establishment for the account.
       * </pre>
       *
       * <code>string establishment_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEstablishmentName() {
        establishmentName_ = getDefaultInstance().getEstablishmentName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the establishment for the account.
       * </pre>
       *
       * <code>string establishment_name = 4;</code>
       * @param value The bytes for establishmentName to set.
       * @return This builder for chaining.
       */
      public Builder setEstablishmentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        establishmentName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object baseUrl_ = "";
      /**
       * <pre>
       * The base URL of the instance this points to.
       * </pre>
       *
       * <code>string base_url = 5;</code>
       * @return The baseUrl.
       */
      public java.lang.String getBaseUrl() {
        java.lang.Object ref = baseUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The base URL of the instance this points to.
       * </pre>
       *
       * <code>string base_url = 5;</code>
       * @return The bytes for baseUrl.
       */
      public com.google.protobuf.ByteString
          getBaseUrlBytes() {
        java.lang.Object ref = baseUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The base URL of the instance this points to.
       * </pre>
       *
       * <code>string base_url = 5;</code>
       * @param value The baseUrl to set.
       * @return This builder for chaining.
       */
      public Builder setBaseUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        baseUrl_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The base URL of the instance this points to.
       * </pre>
       *
       * <code>string base_url = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseUrl() {
        baseUrl_ = getDefaultInstance().getBaseUrl();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The base URL of the instance this points to.
       * </pre>
       *
       * <code>string base_url = 5;</code>
       * @param value The bytes for baseUrl to set.
       * @return This builder for chaining.
       */
      public Builder setBaseUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        baseUrl_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object workspaceName_ = "";
      /**
       * <pre>
       * The display name of the workspace this account is linked to.
       * </pre>
       *
       * <code>string workspace_name = 6;</code>
       * @return The workspaceName.
       */
      public java.lang.String getWorkspaceName() {
        java.lang.Object ref = workspaceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workspaceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The display name of the workspace this account is linked to.
       * </pre>
       *
       * <code>string workspace_name = 6;</code>
       * @return The bytes for workspaceName.
       */
      public com.google.protobuf.ByteString
          getWorkspaceNameBytes() {
        java.lang.Object ref = workspaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workspaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The display name of the workspace this account is linked to.
       * </pre>
       *
       * <code>string workspace_name = 6;</code>
       * @param value The workspaceName to set.
       * @return This builder for chaining.
       */
      public Builder setWorkspaceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        workspaceName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The display name of the workspace this account is linked to.
       * </pre>
       *
       * <code>string workspace_name = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkspaceName() {
        workspaceName_ = getDefaultInstance().getWorkspaceName();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The display name of the workspace this account is linked to.
       * </pre>
       *
       * <code>string workspace_name = 6;</code>
       * @param value The bytes for workspaceName to set.
       * @return This builder for chaining.
       */
      public Builder setWorkspaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        workspaceName_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any tokenCredentials_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> tokenCredentialsBuilder_;
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       * @return Whether the tokenCredentials field is set.
       */
      public boolean hasTokenCredentials() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       * @return The tokenCredentials.
       */
      public com.google.protobuf.Any getTokenCredentials() {
        if (tokenCredentialsBuilder_ == null) {
          return tokenCredentials_ == null ? com.google.protobuf.Any.getDefaultInstance() : tokenCredentials_;
        } else {
          return tokenCredentialsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public Builder setTokenCredentials(com.google.protobuf.Any value) {
        if (tokenCredentialsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tokenCredentials_ = value;
        } else {
          tokenCredentialsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public Builder setTokenCredentials(
          com.google.protobuf.Any.Builder builderForValue) {
        if (tokenCredentialsBuilder_ == null) {
          tokenCredentials_ = builderForValue.build();
        } else {
          tokenCredentialsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public Builder mergeTokenCredentials(com.google.protobuf.Any value) {
        if (tokenCredentialsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            tokenCredentials_ != null &&
            tokenCredentials_ != com.google.protobuf.Any.getDefaultInstance()) {
            getTokenCredentialsBuilder().mergeFrom(value);
          } else {
            tokenCredentials_ = value;
          }
        } else {
          tokenCredentialsBuilder_.mergeFrom(value);
        }
        if (tokenCredentials_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public Builder clearTokenCredentials() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tokenCredentials_ = null;
        if (tokenCredentialsBuilder_ != null) {
          tokenCredentialsBuilder_.dispose();
          tokenCredentialsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public com.google.protobuf.Any.Builder getTokenCredentialsBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return internalGetTokenCredentialsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      public com.google.protobuf.AnyOrBuilder getTokenCredentialsOrBuilder() {
        if (tokenCredentialsBuilder_ != null) {
          return tokenCredentialsBuilder_.getMessageOrBuilder();
        } else {
          return tokenCredentials_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : tokenCredentials_;
        }
      }
      /**
       * <pre>
       * The actual identifiers for the account. Some informations within it may be
       * duplicated.
       * </pre>
       *
       * <code>.google.protobuf.Any token_credentials = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          internalGetTokenCredentialsFieldBuilder() {
        if (tokenCredentialsBuilder_ == null) {
          tokenCredentialsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getTokenCredentials(),
                  getParentForChildren(),
                  isClean());
          tokenCredentials_ = null;
        }
        return tokenCredentialsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:antinote_app.AntinoteAccount)
    }

    // @@protoc_insertion_point(class_scope:antinote_app.AntinoteAccount)
    private static final fr.antinote.antinote_app.protos.Account.AntinoteAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.antinote.antinote_app.protos.Account.AntinoteAccount();
    }

    public static fr.antinote.antinote_app.protos.Account.AntinoteAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AntinoteAccount>
        PARSER = new com.google.protobuf.AbstractParser<AntinoteAccount>() {
      @java.lang.Override
      public AntinoteAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AntinoteAccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AntinoteAccount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fr.antinote.antinote_app.protos.Account.AntinoteAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountRegistryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:antinote_app.AccountRegistry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount> 
        getAccountsList();
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    fr.antinote.antinote_app.protos.Account.AntinoteAccount getAccounts(int index);
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    int getAccountsCount();
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    java.util.List<? extends fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder> 
        getAccountsOrBuilderList();
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder getAccountsOrBuilder(
        int index);

    /**
     * <code>optional string default_account_id = 2;</code>
     * @return Whether the defaultAccountId field is set.
     */
    boolean hasDefaultAccountId();
    /**
     * <code>optional string default_account_id = 2;</code>
     * @return The defaultAccountId.
     */
    java.lang.String getDefaultAccountId();
    /**
     * <code>optional string default_account_id = 2;</code>
     * @return The bytes for defaultAccountId.
     */
    com.google.protobuf.ByteString
        getDefaultAccountIdBytes();
  }
  /**
   * Protobuf type {@code antinote_app.AccountRegistry}
   */
  public static final class AccountRegistry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:antinote_app.AccountRegistry)
      AccountRegistryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "AccountRegistry");
    }
    // Use AccountRegistry.newBuilder() to construct.
    private AccountRegistry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AccountRegistry() {
      accounts_ = java.util.Collections.emptyList();
      defaultAccountId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.antinote.antinote_app.protos.Account.AccountRegistry.class, fr.antinote.antinote_app.protos.Account.AccountRegistry.Builder.class);
    }

    private int bitField0_;
    public static final int ACCOUNTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount> accounts_;
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount> getAccountsList() {
      return accounts_;
    }
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder> 
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    @java.lang.Override
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    @java.lang.Override
    public fr.antinote.antinote_app.protos.Account.AntinoteAccount getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
     */
    @java.lang.Override
    public fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }

    public static final int DEFAULT_ACCOUNT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object defaultAccountId_ = "";
    /**
     * <code>optional string default_account_id = 2;</code>
     * @return Whether the defaultAccountId field is set.
     */
    @java.lang.Override
    public boolean hasDefaultAccountId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string default_account_id = 2;</code>
     * @return The defaultAccountId.
     */
    @java.lang.Override
    public java.lang.String getDefaultAccountId() {
      java.lang.Object ref = defaultAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string default_account_id = 2;</code>
     * @return The bytes for defaultAccountId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDefaultAccountIdBytes() {
      java.lang.Object ref = defaultAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < accounts_.size(); i++) {
        output.writeMessage(1, accounts_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, defaultAccountId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;

          {
            final int count = accounts_.size();
            for (int i = 0; i < count; i++) {
              size += com.google.protobuf.CodedOutputStream
                .computeMessageSizeNoTag(accounts_.get(i));
            }
            size += 1 * count;
          }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, defaultAccountId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.antinote.antinote_app.protos.Account.AccountRegistry)) {
        return super.equals(obj);
      }
      fr.antinote.antinote_app.protos.Account.AccountRegistry other = (fr.antinote.antinote_app.protos.Account.AccountRegistry) obj;

      if (!getAccountsList()
          .equals(other.getAccountsList())) return false;
      if (hasDefaultAccountId() != other.hasDefaultAccountId()) return false;
      if (hasDefaultAccountId()) {
        if (!getDefaultAccountId()
            .equals(other.getDefaultAccountId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAccountsCount() > 0) {
        hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getAccountsList().hashCode();
      }
      if (hasDefaultAccountId()) {
        hash = (37 * hash) + DEFAULT_ACCOUNT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultAccountId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fr.antinote.antinote_app.protos.Account.AccountRegistry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.antinote.antinote_app.protos.Account.AccountRegistry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code antinote_app.AccountRegistry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:antinote_app.AccountRegistry)
        fr.antinote.antinote_app.protos.Account.AccountRegistryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.antinote.antinote_app.protos.Account.AccountRegistry.class, fr.antinote.antinote_app.protos.Account.AccountRegistry.Builder.class);
      }

      // Construct using fr.antinote.antinote_app.protos.Account.AccountRegistry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
        } else {
          accounts_ = null;
          accountsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        defaultAccountId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.antinote.antinote_app.protos.Account.internal_static_antinote_app_AccountRegistry_descriptor;
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AccountRegistry getDefaultInstanceForType() {
        return fr.antinote.antinote_app.protos.Account.AccountRegistry.getDefaultInstance();
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AccountRegistry build() {
        fr.antinote.antinote_app.protos.Account.AccountRegistry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fr.antinote.antinote_app.protos.Account.AccountRegistry buildPartial() {
        fr.antinote.antinote_app.protos.Account.AccountRegistry result = new fr.antinote.antinote_app.protos.Account.AccountRegistry(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(fr.antinote.antinote_app.protos.Account.AccountRegistry result) {
        if (accountsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            accounts_ = java.util.Collections.unmodifiableList(accounts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.accounts_ = accounts_;
        } else {
          result.accounts_ = accountsBuilder_.build();
        }
      }

      private void buildPartial0(fr.antinote.antinote_app.protos.Account.AccountRegistry result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.defaultAccountId_ = defaultAccountId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.antinote.antinote_app.protos.Account.AccountRegistry) {
          return mergeFrom((fr.antinote.antinote_app.protos.Account.AccountRegistry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.antinote.antinote_app.protos.Account.AccountRegistry other) {
        if (other == fr.antinote.antinote_app.protos.Account.AccountRegistry.getDefaultInstance()) return this;
        if (accountsBuilder_ == null) {
          if (!other.accounts_.isEmpty()) {
            if (accounts_.isEmpty()) {
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAccountsIsMutable();
              accounts_.addAll(other.accounts_);
            }
            onChanged();
          }
        } else {
          if (!other.accounts_.isEmpty()) {
            if (accountsBuilder_.isEmpty()) {
              accountsBuilder_.dispose();
              accountsBuilder_ = null;
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              accountsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetAccountsFieldBuilder() : null;
            } else {
              accountsBuilder_.addAllMessages(other.accounts_);
            }
          }
        }
        if (other.hasDefaultAccountId()) {
          defaultAccountId_ = other.defaultAccountId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fr.antinote.antinote_app.protos.Account.AntinoteAccount m =
                    input.readMessage(
                        fr.antinote.antinote_app.protos.Account.AntinoteAccount.parser(),
                        extensionRegistry);
                if (accountsBuilder_ == null) {
                  ensureAccountsIsMutable();
                  accounts_.add(m);
                } else {
                  accountsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                defaultAccountId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount> accounts_ =
        java.util.Collections.emptyList();
      private void ensureAccountsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          accounts_ = new java.util.ArrayList<fr.antinote.antinote_app.protos.Account.AntinoteAccount>(accounts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fr.antinote.antinote_app.protos.Account.AntinoteAccount, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder, fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder> accountsBuilder_;

      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount> getAccountsList() {
        if (accountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accounts_);
        } else {
          return accountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public int getAccountsCount() {
        if (accountsBuilder_ == null) {
          return accounts_.size();
        } else {
          return accountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount getAccounts(int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);
        } else {
          return accountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder setAccounts(
          int index, fr.antinote.antinote_app.protos.Account.AntinoteAccount value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.set(index, value);
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder setAccounts(
          int index, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder addAccounts(fr.antinote.antinote_app.protos.Account.AntinoteAccount value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder addAccounts(
          int index, fr.antinote.antinote_app.protos.Account.AntinoteAccount value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(index, value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder addAccounts(
          fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder addAccounts(
          int index, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder addAllAccounts(
          java.lang.Iterable<? extends fr.antinote.antinote_app.protos.Account.AntinoteAccount> values) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accounts_);
          onChanged();
        } else {
          accountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder clearAccounts() {
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public Builder removeAccounts(int index) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.remove(index);
          onChanged();
        } else {
          accountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder getAccountsBuilder(
          int index) {
        return internalGetAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder getAccountsOrBuilder(
          int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);  } else {
          return accountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public java.util.List<? extends fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder> 
           getAccountsOrBuilderList() {
        if (accountsBuilder_ != null) {
          return accountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accounts_);
        }
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder addAccountsBuilder() {
        return internalGetAccountsFieldBuilder().addBuilder(
            fr.antinote.antinote_app.protos.Account.AntinoteAccount.getDefaultInstance());
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder addAccountsBuilder(
          int index) {
        return internalGetAccountsFieldBuilder().addBuilder(
            index, fr.antinote.antinote_app.protos.Account.AntinoteAccount.getDefaultInstance());
      }
      /**
       * <code>repeated .antinote_app.AntinoteAccount accounts = 1;</code>
       */
      public java.util.List<fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder> 
           getAccountsBuilderList() {
        return internalGetAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.antinote.antinote_app.protos.Account.AntinoteAccount, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder, fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder> 
          internalGetAccountsFieldBuilder() {
        if (accountsBuilder_ == null) {
          accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.antinote.antinote_app.protos.Account.AntinoteAccount, fr.antinote.antinote_app.protos.Account.AntinoteAccount.Builder, fr.antinote.antinote_app.protos.Account.AntinoteAccountOrBuilder>(
                  accounts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          accounts_ = null;
        }
        return accountsBuilder_;
      }

      private java.lang.Object defaultAccountId_ = "";
      /**
       * <code>optional string default_account_id = 2;</code>
       * @return Whether the defaultAccountId field is set.
       */
      public boolean hasDefaultAccountId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string default_account_id = 2;</code>
       * @return The defaultAccountId.
       */
      public java.lang.String getDefaultAccountId() {
        java.lang.Object ref = defaultAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          defaultAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string default_account_id = 2;</code>
       * @return The bytes for defaultAccountId.
       */
      public com.google.protobuf.ByteString
          getDefaultAccountIdBytes() {
        java.lang.Object ref = defaultAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          defaultAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string default_account_id = 2;</code>
       * @param value The defaultAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultAccountId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        defaultAccountId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string default_account_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultAccountId() {
        defaultAccountId_ = getDefaultInstance().getDefaultAccountId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string default_account_id = 2;</code>
       * @param value The bytes for defaultAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        defaultAccountId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:antinote_app.AccountRegistry)
    }

    // @@protoc_insertion_point(class_scope:antinote_app.AccountRegistry)
    private static final fr.antinote.antinote_app.protos.Account.AccountRegistry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.antinote.antinote_app.protos.Account.AccountRegistry();
    }

    public static fr.antinote.antinote_app.protos.Account.AccountRegistry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountRegistry>
        PARSER = new com.google.protobuf.AbstractParser<AccountRegistry>() {
      @java.lang.Override
      public AccountRegistry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccountRegistry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountRegistry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fr.antinote.antinote_app.protos.Account.AccountRegistry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_antinote_app_AntinoteAccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_antinote_app_AntinoteAccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_antinote_app_AccountRegistry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_antinote_app_AccountRegistry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/account.proto\022\014antinote_app\032\031go" +
      "ogle/protobuf/any.proto\"\265\001\n\017AntinoteAcco" +
      "unt\022\013\n\003uid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010userna" +
      "me\030\003 \001(\t\022\032\n\022establishment_name\030\004 \001(\t\022\020\n\010" +
      "base_url\030\005 \001(\t\022\026\n\016workspace_name\030\006 \001(\t\022/" +
      "\n\021token_credentials\030\007 \001(\0132\024.google.proto" +
      "buf.Any\"z\n\017AccountRegistry\022/\n\010accounts\030\001" +
      " \003(\0132\035.antinote_app.AntinoteAccount\022\037\n\022d" +
      "efault_account_id\030\002 \001(\tH\000\210\001\001B\025\n\023_default" +
      "_account_idB#\n\037fr.antinote.antinote_app." +
      "protosH\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_antinote_app_AntinoteAccount_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_antinote_app_AntinoteAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_antinote_app_AntinoteAccount_descriptor,
        new java.lang.String[] { "Uid", "Name", "Username", "EstablishmentName", "BaseUrl", "WorkspaceName", "TokenCredentials", });
    internal_static_antinote_app_AccountRegistry_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_antinote_app_AccountRegistry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_antinote_app_AccountRegistry_descriptor,
        new java.lang.String[] { "Accounts", "DefaultAccountId", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
