syntax = "proto3";
package antinote_app;
option java_package = "fr.antinote.antinote_app.protos";
option java_multiple_files = true;

import "google/protobuf/any.proto";

message EncryptedCredentials {
  // The token that's used to login.
  bytes credential_data = 1;
  // The IV that needs to be used to decrypt [credential_data].
  bytes credential_iv = 2;

  // Needs to be decrypted to decrypt [credential_data] and [credential_iv]. We do this to ask the
  // user for biometrics once upon login and being able to do multiple operations at once.
  bytes dek_data = 3;
  // IV used to decrypt [dek_data].
  bytes dek_iv = 4;
}

message AntinoteAccount {
  // An internal Unique IDentifier used as a primary key to reference accounts
  // throughout the app.
  string uid = 1;
  // The full name of the account holder.
  string name = 2;
  // The username of the account.
  string username = 3;
  // The name of the establishment for the account.
  string establishment_name = 4;
  // The base URL of the instance this points to.
  string base_url = 5;
  // The display name of the workspace this account is linked to.
  string workspace_name = 6;
  // The actual identifiers for the account. Some information within it may be
  // duplicated. If [store_securely] is [true], this will be [EncryptedCredentials].
  google.protobuf.Any token_credentials = 7;
  // Whether this account is determined to be defunct, and is blocked from ever
  // being logged to when it is the [AccountRegistry.default_account_id].
  bool invalid = 8;
  // Whether to store the account in the Keystore of the platform.
  bool store_securely = 9;
}

message AccountRegistry {
  repeated AntinoteAccount accounts = 1;
  optional string default_account_id = 2;
}